app = 'future-you-server'
primary_region = 'ord'

[build]

[env]
  PORT = '3005'
  DATA_DIR = '/data'
  ALLOWED_ORIGINS = '*'

[http_service]
  internal_port = 3005
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[mounts]
  source = 'futureyou_data'
  destination = '/data'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
